// <auto-generated />
namespace SportsWebPt.Platform.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.8.3")]
    public sealed partial class Episodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Episodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201408192042424_Episodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
