// <auto-generated />
namespace SportsWebPt.Platform.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class SportsWebPtBeta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SportsWebPtBeta));
        
        string IMigrationMetadata.Id
        {
            get { return "201402170038144_SportsWebPtBeta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
