// <auto-generated />
namespace SportsWebPt.Platform.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TherapistShare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TherapistShare));
        
        string IMigrationMetadata.Id
        {
            get { return "201407290350324_TherapistShare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
