// <auto-generated />
namespace SportsWebPt.Platform.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TreatmentDescType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TreatmentDescType));
        
        string IMigrationMetadata.Id
        {
            get { return "201402250435587_TreatmentDescType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
