//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsWebPt.Common.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsWebPt.Common.Utilities.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&quot;{0}\&quot; cannot be blank.&quot;.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&quot;{0}\&quot; cannot be empty guid.&quot;.
        /// </summary>
        public static string CannotBeEmptyGuid {
            get {
                return ResourceManager.GetString("CannotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Collection cannot be empty.&quot;.
        /// </summary>
        public static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A header record cannot be inserted since a regular record has already been written..
        /// </summary>
        public static string CsvAlreadyWroteFirstRecord {
            get {
                return ResourceManager.GetString("CsvAlreadyWroteFirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv data does not exist..
        /// </summary>
        public static string CsvDatasetIsEmpty {
            get {
                return ResourceManager.GetString("CsvDatasetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header record is already set..
        /// </summary>
        public static string CsvHeaderRecordAlreadySet {
            get {
                return ResourceManager.GetString("CsvHeaderRecordAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row has {0} columns and should have {1} columns..
        /// </summary>
        public static string CsvTooManyColumnsInRow {
            get {
                return ResourceManager.GetString("CsvTooManyColumnsInRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value delimiter cannot be the same as space character..
        /// </summary>
        public static string CsvValueDelimiterCannotBeSpace {
            get {
                return ResourceManager.GetString("CsvValueDelimiterCannotBeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value separator cannot be the same as the delimiter..
        /// </summary>
        public static string CsvValueSeparatorCannotBeSameAsDelimiter {
            get {
                return ResourceManager.GetString("CsvValueSeparatorCannotBeSameAsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value separator cannot be the same as space character..
        /// </summary>
        public static string CsvValueSeparatorCannotBeSpace {
            get {
                return ResourceManager.GetString("CsvValueSeparatorCannotBeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with name {0} could not be found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&quot;{0}\&quot; is not a valid email address.&quot;.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &apos;{0}&apos; is not defined for enumeration &apos;{1}&apos;..
        /// </summary>
        public static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &apos;{0}&apos; is not valid for flags enumeration &apos;{1}&apos;..
        /// </summary>
        public static string InvalidEnumForFlags {
            get {
                return ResourceManager.GetString("InvalidEnumForFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &apos;{0}&apos; is defined for enumeration &apos;{1}&apos; but it is not permitted in this context..
        /// </summary>
        public static string InvalidEnumPermission {
            get {
                return ResourceManager.GetString("InvalidEnumPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} cannot be an empty Guid..
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&quot;{0}\&quot; cannot be more than {1} character.&quot;.
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&quot;{0}\&quot; is not a valid web url.&quot;.
        /// </summary>
        public static string InvalidWebUrl {
            get {
                return ResourceManager.GetString("InvalidWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} must be between \&quot;{1}\&quot;-\&quot;{2}\&quot;.&quot;.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
    }
}
